# Generated by Django 5.1.6 on 2025-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_alter_post_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('subject', models.CharField(verbose_name='موضوع')),
                ('status', models.CharField(verbose_name='وضعیت')),
            ],
        ),
    ]
