# Generated by Django 5.1.6 on 2025-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_posts_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان مطالعه'),
        ),
    ]
