# Generated by Django 5.2 on 2025-05-11 12:27

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_image_image_image_file_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[150, 150], upload_to='images/'),
        ),
    ]
